# Site settings
title: qshZone
email: me@qshzone.ru
description: > # this means to ignore newlines until "baseurl:"
  О мыслях, идеях, опыте и впечатлениях - о жизни.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qshzone.ru" # the base hostname & protocol for your site
twitter_username: PavelQuash
github_username:  PavelQuash

# Build settings
markdown: kramdown
highlighter: pygments