# Site settings
title: qshZone
description: > # this means to ignore newlines until "baseurl:"
  О мыслях, идеях, опыте и впечатлениях - о жизни.
timezone: Asia/Yekaterinburg

# Routing
url: "http://qshzone.ru" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:title # Url post naming

# Build settings
markdown: kramdown
highlighter: pygments
exclude:
  - j-buildSite.cmd
  - j-startServer.cmd
  
# Author
author:
  twitter: PavelQuash
  github: PavelQuash
